#pragma once

static const char INDEX_HTML[] =
"<!DOCTYPE html>"
"<html>"
"<head>"
"<meta charset=\"utf-8\">"
"<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">"
"<title>ESP32 \xe9\x85\x8d\xe7\xbd\xae</title>"
"<style>"
"body{font-family:sans-serif;margin:20px;}"
".tab-buttons button{padding:8px 16px;margin-right:4px;border:1px solid #ccc;"
"background:#f0f0f0;cursor:pointer;border-radius:4px;}"
".tab-buttons button.active{background:#007bff;color:#fff;}"
".tab-content{display:none;margin-top:16px;}"
".tab-content.active{display:block;}"
"input{padding:8px;margin:4px 0;width:220px;box-sizing:border-box;}"
"button.save{padding:8px 20px;background:#28a745;color:#fff;border:none;"
"border-radius:4px;cursor:pointer;}"
"button.save:disabled{background:#999;cursor:not-allowed;}"
"#status{margin-top:12px;font-weight:bold;}"
".ok{color:green;} .err{color:red;}"
"</style>"
"</head>"
"<body>"
"<h1>ESP32 \xe9\x85\x8d\xe7\xbd\xae\xe9\xa1\xb5\xe9\x9d\xa2</h1>"

"<div class=\"tab-buttons\">"
"<button class=\"active\" onclick=\"showTab('tab-wifi',this)\">Wi-Fi \xe8\xae\xbe\xe7\xbd\xae</button>"
"<button onclick=\"showTab('tab-ota',this)\">OTA \xe5\x8d\x87\xe7\xba\xa7</button>"
"<button onclick=\"showTab('tab-info',this)\">\xe8\xae\xbe\xe5\xa4\x87\xe4\xbf\xa1\xe6\x81\xaf</button>"
"</div>"

"<div id=\"tab-wifi\" class=\"tab-content active\">"
"<h2>\xe4\xbf\xae\xe6\x94\xb9 Wi-Fi</h2>"
"<div><label>SSID</label><br>"
"<input type=\"text\" id=\"ssid\" placeholder=\"\xe8\xbe\x93\xe5\x85\xa5 Wi-Fi \xe5\x90\x8d\xe7\xa7\xb0\"></div>"
"<div><label>\xe5\xaf\x86\xe7\xa0\x81</label><br>"
"<input type=\"text\" id=\"passwd\" placeholder=\"\xe8\xbe\x93\xe5\x85\xa5 Wi-Fi \xe5\xaf\x86\xe7\xa0\x81\"></div>"
"<button class=\"save\" id=\"saveBtn\" onclick=\"saveWifi()\">\xe4\xbf\x9d\xe5\xad\x98</button>"
"<div id=\"status\"></div>"
"</div>"

"<div id=\"tab-ota\" class=\"tab-content\">"
"<h2>OTA \xe5\x8d\x87\xe7\xba\xa7</h2>"
"<div><label>\xe5\x9b\xba\xe4\xbb\xb6\xe5\x9c\xb0\xe5\x9d\x80</label><br>"
"<input type=\"text\" id=\"ota_uri\" placeholder=\"https://example.com/firmware.bin\" style=\"width:320px;\"></div>"
"<button class=\"save\" id=\"otaBtn\" onclick=\"startOta()\">\xe5\x8d\x87\xe7\xba\xa7</button>"
"<div id=\"otaStatus\"></div>"
"</div>"

"<div id=\"tab-info\" class=\"tab-content\">"
"<h2>\xe8\xae\xbe\xe5\xa4\x87\xe4\xbf\xa1\xe6\x81\xaf</h2>"
"<p>\xe8\x8a\xaf\xe7\x89\x87\xef\xbc\x9a ESP32-S3</p>"
"<p>\xe7\x8a\xb6\xe6\x80\x81\xef\xbc\x9a\xe8\xbf\x90\xe8\xa1\x8c\xe4\xb8\xad</p>"
"</div>"

"<script>"
"function showTab(id,btn){"
"  document.querySelectorAll('.tab-content').forEach(e=>e.classList.remove('active'));"
"  document.querySelectorAll('.tab-buttons button').forEach(e=>e.classList.remove('active'));"
"  document.getElementById(id).classList.add('active');"
"  btn.classList.add('active');"
"}"
"function saveWifi(){"
"  var ssid=document.getElementById('ssid').value.trim();"
"  var passwd=document.getElementById('passwd').value.trim();"
"  var status=document.getElementById('status');"
"  var btn=document.getElementById('saveBtn');"
"  if(!ssid||!passwd){status.className='err';status.textContent='\xe8\xaf\xb7\xe5\xa1\xab\xe5\x86\x99 SSID \xe5\x92\x8c\xe5\xaf\x86\xe7\xa0\x81';return;}"
"  btn.disabled=true; btn.textContent='\xe4\xbf\x9d\xe5\xad\x98\xe4\xb8\xad...';"
"  status.className=''; status.textContent='';"
"  var body=new URLSearchParams();"
"  body.append('ssid',ssid); body.append('passwd',passwd);"
"  fetch('/wifi_sta',{method:'POST',"
"    headers:{'Content-Type':'application/x-www-form-urlencoded'},"
"    body:body.toString()})"
"  .then(function(r){if(!r.ok)throw new Error('HTTP '+r.status);return r.text();})"
"  .then(function(t){status.className='ok';status.textContent='\xe2\x9c\x85 '+t;})"
"  .catch(function(e){status.className='err';status.textContent='\xe2\x9d\x8c '+e.message;})"
"  .finally(function(){btn.disabled=false;btn.textContent='\xe4\xbf\x9d\xe5\xad\x98';});"
"}"
"function startOta(){"
"  var uri=document.getElementById('ota_uri').value.trim();"
"  var status=document.getElementById('otaStatus');"
"  var btn=document.getElementById('otaBtn');"
"  if(!uri){status.className='err';status.textContent='\xe8\xaf\xb7\xe8\xbe\x93\xe5\x85\xa5\xe5\x9b\xba\xe4\xbb\xb6\xe5\x9c\xb0\xe5\x9d\x80';return;}"
"  btn.disabled=true; btn.textContent='\xe5\x8d\x87\xe7\xba\xa7\xe4\xb8\xad\xef\xbc\x8c\xe8\xaf\xb7\xe5\x8b\xbf\xe6\x96\xad\xe7\x94\xb5...';"
"  status.className=''; status.textContent='';"
"  var body=new URLSearchParams();"
"  body.append('ota_uri',uri);"
"  fetch('/ota',{method:'POST',"
"    headers:{'Content-Type':'application/x-www-form-urlencoded'},"
"    body:body.toString()})"
"  .then(function(r){return r.text().then(function(t){return {ok:r.ok,text:t};});})"
"  .then(function(res){"
"    if(res.ok){"
"      status.className='ok';status.textContent='\xe2\x9c\x85 '+res.text;"
"    }else{"
"      status.className='err';status.textContent='\xe2\x9d\x8c '+res.text;"
"    }"
"  })"
"  .catch(function(e){status.className='err';status.textContent='\xe2\x9d\x8c '+e.message;"
"    btn.disabled=false;btn.textContent='\xe5\x8d\x87\xe7\xba\xa7';});"
"}"
"</script>"
"</body>"
"</html>";
